const animationsTypes = {
  BEAM_ANIMATION: 'BEAM_ANIMATION',
  ENGINE_ANIMATION: 'ENGINE_ANIMAITON',
  FLY_TO_COW_ANIMATION: 'FLY_TO_COW_ANIMATION',
  FLY_TO_LAUNCHING_POSITION_ANIMATION: 'FLY_TO_LAUNCHING_POSITION_ANIMATION',
  HOVER_OVER_COW_ANIMATION: 'HOVER_OVER_COW_ANIMATION',
  LIFT_COW_UP_ANIMATION: 'LIFT_COW_UP_ANIMATION',
  ORBITING_ANIMATION: 'ORBITING_ANIMATION',
  PUT_COW_DOWN_ANIMATION: 'PUT_COW_DOWN_ANIMATION',
};

const refsTypes = {
  EARTH_REF: 'EARTH_REF',
  LANGUAGE_CONTROLLER_REF: 'LANGUAGE_CONTROLLER_REF',
  TOPBAR_MENU_REF: 'TOPBAR_MENU_REF',
  UFO_REF: 'UFO_REF',
};

export { animationsTypes, refsTypes };
