const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const CHANGE_NAVIGATION_VISIBILITY = 'CHANGE_NAVIGATION_VISIBILITY';
const CHANGE_SIDEBAR_STATE = 'CHANGE_SIDEBAR_STATE';
const SET_CLICKED_COW_REF = 'SET_CLICKED_COW_REF';
const UPDATE_UFO_POSITION = 'UPDATE_UFO_POSITION';
const GLOBAL_REFS = 'GLOBAL_REFS';
const ANIMATIONS = 'ANIMATIONS';
const QUEUE_COMMAND = 'QUEUE_COMMAND';
const REMOVE_COMMAND_FROM_QUEUE = 'REMOVE_COMMAND_FROM_QUEUE';
const DISPLAY_COMMAND = 'DISPLAY_COMMAND';
const CLEAR_TERMINAL = 'CLEAR_TERMINAL';
const CHANGE_DIRECTORY = 'CHANGE_DIRECTORY';
const SET_GAME_STATE = 'SET_GAME_STATE';
const UPDATE_ASTEROID_DATA = 'UPDATE_ASTEROID_DATA';
const UPDATE_ASTEROID_POSITION = 'UPDATE_ASTEROID_POSITION';
const CLEAN_ASTEROID_DATA = 'CLEAN_ASTEROID_DATA';
const ADD_ASTEROID_HIT = 'ADD_ASTEROID_HIT';
const UPDATE_KEY_STATE = 'UPDATE_KEY_STATE';
const SET_CROSSHAIR_ANGLE = 'SET_CROSSHAIR_ANGLE';
const ADD_EXPLOSION = 'ADD_EXPLOSION';
const REMOVE_EXPLOSION = 'REMOVE_EXPLOSION';
const ADD_UFO_HIT = 'ADD_UFO_HIT';
const CLEAR_UFO_HITS = 'CLEAR_UFO_HITS';
const UPDATE_TECHNOLOGIES = 'UPDATE_TECHNOLOGIES';

export default {
  CHANGE_LANGUAGE,
  CHANGE_NAVIGATION_VISIBILITY,
  CHANGE_SIDEBAR_STATE,
  SET_CLICKED_COW_REF,
  UPDATE_UFO_POSITION,
  GLOBAL_REFS,
  ANIMATIONS,
  QUEUE_COMMAND,
  REMOVE_COMMAND_FROM_QUEUE,
  DISPLAY_COMMAND,
  CLEAR_TERMINAL,
  CHANGE_DIRECTORY,
  SET_GAME_STATE,
  UPDATE_ASTEROID_DATA,
  UPDATE_ASTEROID_POSITION,
  CLEAN_ASTEROID_DATA,
  ADD_ASTEROID_HIT,
  UPDATE_KEY_STATE,
  SET_CROSSHAIR_ANGLE,
  ADD_EXPLOSION,
  REMOVE_EXPLOSION,
  ADD_UFO_HIT,
  CLEAR_UFO_HITS,
  UPDATE_TECHNOLOGIES,
};
