const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const SET_FULLPAGE_API = 'SET_FULLPAGE_API';
const CHANGE_SIDEBAR_STATE = 'CHANGE_SIDEBAR_STATE';
const SET_HOME_UFO_CONTAINER_DIMENSION_AND_POSITION = 'SET_HOME_UFO_CONTAINER_DIMENSION_AND_POSITION';
const SET_HOVERED_COW = 'SET_HOVERED_COW';

export default {
  CHANGE_LANGUAGE,
  SET_FULLPAGE_API,
  CHANGE_SIDEBAR_STATE,
  SET_HOME_UFO_CONTAINER_DIMENSION_AND_POSITION,
  SET_HOVERED_COW,
};
