const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';
const ADD_ASTEROID = 'ADD_ASTEROID';
const REMOVE_ASTEROID = 'REMOVE_ASTEROID';
const CLEAR_ASTEROIDS = 'CLEAR_ASTEROIDS';
const ADD_ASTEROID_HIT = 'ADD_ASTEROID_HIT';
const CLEAR_ASTEROIDS_HITS = 'CLEAR_ASTEROIDS_HITS';
const UPDATE_KEY_STATE = 'UPDATE_KEY_STATE';
const SET_CROSSHAIR_ANGLE = 'SET_CROSSHAIR_ANGLE';
const ADD_EXPLOSION = 'ADD_EXPLOSION';
const REMOVE_EXPLOSION = 'REMOVE_EXPLOSION';
const ADD_UFO_HIT = 'ADD_UFO_HIT';
const CLEAR_UFO_HITS = 'CLEAR_UFO_HITS';
const UPDATE_TECHNOLOGIES = 'UPDATE_TECHNOLOGIES';
const CLEAR_TECHNOLOGIES = 'CLEAR_TECHNOLOGIES';

export default {
  UPDATE_GAME_STATE,
  ADD_ASTEROID,
  REMOVE_ASTEROID,
  CLEAR_ASTEROIDS,
  ADD_ASTEROID_HIT,
  CLEAR_ASTEROIDS_HITS,
  UPDATE_KEY_STATE,
  SET_CROSSHAIR_ANGLE,
  ADD_EXPLOSION,
  REMOVE_EXPLOSION,
  ADD_UFO_HIT,
  CLEAR_UFO_HITS,
  UPDATE_TECHNOLOGIES,
  CLEAR_TECHNOLOGIES,
};
