const SET_GAME_STATE = 'SET_GAME_STATE';
const ADD_ASTEROID_HIT = 'ADD_ASTEROID_HIT';
const UPDATE_KEY_STATE = 'UPDATE_KEY_STATE';
const SET_CROSSHAIR_ANGLE = 'SET_CROSSHAIR_ANGLE';
const ADD_EXPLOSION = 'ADD_EXPLOSION';
const REMOVE_EXPLOSION = 'REMOVE_EXPLOSION';
const ADD_UFO_HIT = 'ADD_UFO_HIT';
const CLEAR_UFO_HITS = 'CLEAR_UFO_HITS';
const UPDATE_TECHNOLOGIES = 'UPDATE_TECHNOLOGIES';

export default {
  SET_GAME_STATE,
  ADD_ASTEROID_HIT,
  UPDATE_KEY_STATE,
  SET_CROSSHAIR_ANGLE,
  ADD_EXPLOSION,
  REMOVE_EXPLOSION,
  ADD_UFO_HIT,
  CLEAR_UFO_HITS,
  UPDATE_TECHNOLOGIES,
};
