const QUEUE_COMMAND = 'QUEUE_COMMAND';
const REMOVE_COMMAND_FROM_QUEUE = 'REMOVE_COMMAND_FROM_QUEUE';
const DISPLAY_COMMAND = 'DISPLAY_COMMAND';
const CLEAR_TERMINAL = 'CLEAR_TERMINAL';
const CHANGE_DIRECTORY = 'CHANGE_DIRECTORY';
const SET_CLICKED_COW = 'SET_CLICKED_COW';

export default {
  QUEUE_COMMAND,
  REMOVE_COMMAND_FROM_QUEUE,
  DISPLAY_COMMAND,
  CLEAR_TERMINAL,
  CHANGE_DIRECTORY,
  SET_CLICKED_COW,
};
