const SHOW_DIALOG = 'SHOW_DIALOG';
const HIDE_DIALOG = 'HIDE_DIALOG';
const TURN_SIGNALS_ON = 'TURN_SIGNALS_ON';
const TURN_SIGNALS_OFF = 'TURN_SIGNALS_OFF';

export default {
  SHOW_DIALOG,
  HIDE_DIALOG,
  TURN_SIGNALS_ON,
  TURN_SIGNALS_OFF,
};
